version: '3.8'

services:
  warranty-validation-db:
    image: mysql:latest
    volumes:
      - ./warranty_validation_service/db/:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: warranty_validation_db
    ports:
      - "3309:3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  warranty-validation-service:
    build:
      context: ./warranty_validation_service
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - warranty-validation-db
    restart: always

  warranty-claim-orchestrator:
    build:
      context: ./warranty_claim_orchestrator
      dockerfile: Dockerfile
    ports:
      - "5001:5000"
    depends_on:
      - warranty-validation-service
    restart: always